begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright 2011 The Apache Software Foundation.  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|webconsole
operator|.
name|http
package|;
end_package

begin_class
specifier|public
class|class
name|WebDetail
block|{
specifier|private
name|long
name|bundleId
decl_stmt|;
specifier|private
name|String
name|contextPath
decl_stmt|;
specifier|private
name|String
name|state
decl_stmt|;
specifier|private
name|String
name|webState
decl_stmt|;
specifier|public
name|long
name|getBundleId
parameter_list|()
block|{
return|return
name|bundleId
return|;
block|}
specifier|public
name|void
name|setBundleId
parameter_list|(
name|long
name|bundleId
parameter_list|)
block|{
name|this
operator|.
name|bundleId
operator|=
name|bundleId
expr_stmt|;
block|}
specifier|public
name|String
name|getContextPath
parameter_list|()
block|{
return|return
name|contextPath
return|;
block|}
specifier|public
name|void
name|setContextPath
parameter_list|(
name|String
name|contextPath
parameter_list|)
block|{
name|this
operator|.
name|contextPath
operator|=
name|contextPath
expr_stmt|;
block|}
specifier|public
name|String
name|getState
parameter_list|()
block|{
return|return
name|state
return|;
block|}
specifier|public
name|void
name|setState
parameter_list|(
name|String
name|state
parameter_list|)
block|{
name|this
operator|.
name|state
operator|=
name|state
expr_stmt|;
block|}
specifier|public
name|String
name|getWebState
parameter_list|()
block|{
return|return
name|webState
return|;
block|}
specifier|public
name|void
name|setWebState
parameter_list|(
name|String
name|webState
parameter_list|)
block|{
name|this
operator|.
name|webState
operator|=
name|webState
expr_stmt|;
block|}
block|}
end_class

end_unit

