begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|dev
operator|.
name|command
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|commands
operator|.
name|Command
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|Bundle
import|;
end_import

begin_comment
comment|/**  * Command for enabling/disabling debug logging on a bundle and calculating the difference in  * wired imports.  */
end_comment

begin_class
annotation|@
name|Command
argument_list|(
name|scope
operator|=
literal|"dev"
argument_list|,
name|name
operator|=
literal|"dynamic-import"
argument_list|,
name|description
operator|=
literal|"Enables/disables dynamic-import for a given bundle."
argument_list|)
specifier|public
class|class
name|DynamicImport
extends|extends
name|AbstractBundleCommand
block|{
annotation|@
name|Override
specifier|protected
name|void
name|doExecute
parameter_list|(
name|Bundle
name|bundle
parameter_list|)
throws|throws
name|Exception
block|{
if|if
condition|(
name|devService
operator|.
name|isDynamicImport
argument_list|(
name|bundle
argument_list|)
condition|)
block|{
name|System
operator|.
name|out
operator|.
name|printf
argument_list|(
literal|"Disabling dynamic imports on bundle %s%n"
argument_list|,
name|bundle
argument_list|)
expr_stmt|;
name|devService
operator|.
name|disableDynamicImports
argument_list|(
name|bundle
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|System
operator|.
name|out
operator|.
name|printf
argument_list|(
literal|"Enabling dynamic imports on bundle %s%n"
argument_list|,
name|bundle
argument_list|)
expr_stmt|;
name|devService
operator|.
name|enableDynamicImports
argument_list|(
name|bundle
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

