begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|karaf
operator|.
name|gshell
operator|.
name|features
operator|.
name|internal
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|karaf
operator|.
name|gshell
operator|.
name|features
operator|.
name|Feature
import|;
end_import

begin_comment
comment|/**  * Test cases for {@link FeaturesServiceImpl}  */
end_comment

begin_class
specifier|public
class|class
name|FeaturesServiceImplTest
extends|extends
name|TestCase
block|{
specifier|public
name|void
name|testGetFeature
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
name|features
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
name|versions
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|()
decl_stmt|;
name|FeatureImpl
name|feature
init|=
operator|new
name|FeatureImpl
argument_list|(
literal|"transaction"
argument_list|)
decl_stmt|;
name|versions
operator|.
name|put
argument_list|(
literal|"1.0.0"
argument_list|,
name|feature
argument_list|)
expr_stmt|;
name|features
operator|.
name|put
argument_list|(
literal|"transaction"
argument_list|,
name|versions
argument_list|)
expr_stmt|;
specifier|final
name|FeaturesServiceImpl
name|impl
init|=
operator|new
name|FeaturesServiceImpl
argument_list|()
block|{
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
name|getFeatures
parameter_list|()
throws|throws
name|Exception
block|{
return|return
name|features
return|;
block|}
empty_stmt|;
block|}
decl_stmt|;
name|assertNotNull
argument_list|(
name|impl
operator|.
name|getFeature
argument_list|(
literal|"transaction"
argument_list|,
name|FeatureImpl
operator|.
name|DEFAULT_VERSION
argument_list|)
argument_list|)
expr_stmt|;
name|assertSame
argument_list|(
name|feature
argument_list|,
name|impl
operator|.
name|getFeature
argument_list|(
literal|"transaction"
argument_list|,
name|FeatureImpl
operator|.
name|DEFAULT_VERSION
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testGetFeatureStripVersion
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
name|features
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
name|versions
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|()
decl_stmt|;
name|FeatureImpl
name|feature
init|=
operator|new
name|FeatureImpl
argument_list|(
literal|"transaction"
argument_list|)
decl_stmt|;
name|versions
operator|.
name|put
argument_list|(
literal|"1.0.0"
argument_list|,
name|feature
argument_list|)
expr_stmt|;
name|features
operator|.
name|put
argument_list|(
literal|"transaction"
argument_list|,
name|versions
argument_list|)
expr_stmt|;
specifier|final
name|FeaturesServiceImpl
name|impl
init|=
operator|new
name|FeaturesServiceImpl
argument_list|()
block|{
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
name|getFeatures
parameter_list|()
throws|throws
name|Exception
block|{
return|return
name|features
return|;
block|}
empty_stmt|;
block|}
decl_stmt|;
name|assertNotNull
argument_list|(
name|impl
operator|.
name|getFeature
argument_list|(
literal|"transaction"
argument_list|,
literal|"  1.0.0  "
argument_list|)
argument_list|)
expr_stmt|;
name|assertSame
argument_list|(
name|feature
argument_list|,
name|impl
operator|.
name|getFeature
argument_list|(
literal|"transaction"
argument_list|,
literal|"  1.0.0   "
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testGetFeatureNotAvailable
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
name|features
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
name|versions
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|()
decl_stmt|;
name|versions
operator|.
name|put
argument_list|(
literal|"1.0.0"
argument_list|,
operator|new
name|FeatureImpl
argument_list|(
literal|"transaction"
argument_list|)
argument_list|)
expr_stmt|;
name|features
operator|.
name|put
argument_list|(
literal|"transaction"
argument_list|,
name|versions
argument_list|)
expr_stmt|;
specifier|final
name|FeaturesServiceImpl
name|impl
init|=
operator|new
name|FeaturesServiceImpl
argument_list|()
block|{
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
name|getFeatures
parameter_list|()
throws|throws
name|Exception
block|{
return|return
name|features
return|;
block|}
empty_stmt|;
block|}
decl_stmt|;
name|assertNull
argument_list|(
name|impl
operator|.
name|getFeature
argument_list|(
literal|"activemq"
argument_list|,
name|FeatureImpl
operator|.
name|DEFAULT_VERSION
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testGetFeatureHighestAvailable
parameter_list|()
throws|throws
name|Exception
block|{
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
name|features
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
name|versions
init|=
operator|new
name|HashMap
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|()
decl_stmt|;
name|versions
operator|.
name|put
argument_list|(
literal|"1.0.0"
argument_list|,
operator|new
name|FeatureImpl
argument_list|(
literal|"transaction"
argument_list|,
literal|"1.0.0"
argument_list|)
argument_list|)
expr_stmt|;
name|versions
operator|.
name|put
argument_list|(
literal|"2.0.0"
argument_list|,
operator|new
name|FeatureImpl
argument_list|(
literal|"transaction"
argument_list|,
literal|"2.0.0"
argument_list|)
argument_list|)
expr_stmt|;
name|features
operator|.
name|put
argument_list|(
literal|"transaction"
argument_list|,
name|versions
argument_list|)
expr_stmt|;
specifier|final
name|FeaturesServiceImpl
name|impl
init|=
operator|new
name|FeaturesServiceImpl
argument_list|()
block|{
specifier|protected
name|Map
argument_list|<
name|String
argument_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Feature
argument_list|>
argument_list|>
name|getFeatures
parameter_list|()
throws|throws
name|Exception
block|{
return|return
name|features
return|;
block|}
empty_stmt|;
block|}
decl_stmt|;
name|assertNotNull
argument_list|(
name|impl
operator|.
name|getFeature
argument_list|(
literal|"transaction"
argument_list|,
name|FeatureImpl
operator|.
name|DEFAULT_VERSION
argument_list|)
argument_list|)
expr_stmt|;
name|assertSame
argument_list|(
literal|"2.0.0"
argument_list|,
name|impl
operator|.
name|getFeature
argument_list|(
literal|"transaction"
argument_list|,
name|FeatureImpl
operator|.
name|DEFAULT_VERSION
argument_list|)
operator|.
name|getVersion
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

