begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|features
operator|.
name|internal
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|easymock
operator|.
name|EasyMock
operator|.
name|replay
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|easymock
operator|.
name|EasyMock
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|Bundle
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|BundleContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|Constants
import|;
end_import

begin_class
specifier|public
class|class
name|BundleManagerTest
extends|extends
name|TestBase
block|{
annotation|@
name|Test
specifier|public
name|void
name|testfindBundlestoRefreshWithHostToRefresh
parameter_list|()
throws|throws
name|Exception
block|{
name|Bundle
name|hostBundle
init|=
name|createDummyBundle
argument_list|(
literal|12345l
argument_list|,
literal|"Host"
argument_list|,
name|headers
argument_list|()
argument_list|)
decl_stmt|;
name|Bundle
name|fragmentBundle
init|=
name|createDummyBundle
argument_list|(
literal|54321l
argument_list|,
literal|"fragment"
argument_list|,
name|headers
argument_list|(
name|Constants
operator|.
name|FRAGMENT_HOST
argument_list|,
literal|"Host"
argument_list|)
argument_list|)
decl_stmt|;
name|BundleContext
name|bundleContext
init|=
name|EasyMock
operator|.
name|createMock
argument_list|(
name|BundleContext
operator|.
name|class
argument_list|)
decl_stmt|;
name|BundleManager
name|bundleManager
init|=
operator|new
name|BundleManager
argument_list|(
name|bundleContext
argument_list|)
decl_stmt|;
comment|// Host was already installed, fragment is new
name|Set
argument_list|<
name|Bundle
argument_list|>
name|existing
init|=
operator|new
name|HashSet
argument_list|<
name|Bundle
argument_list|>
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
name|hostBundle
argument_list|,
name|fragmentBundle
argument_list|)
argument_list|)
decl_stmt|;
name|Set
argument_list|<
name|Bundle
argument_list|>
name|installed
init|=
operator|new
name|HashSet
argument_list|<
name|Bundle
argument_list|>
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
name|fragmentBundle
argument_list|)
argument_list|)
decl_stmt|;
name|replay
argument_list|(
name|bundleContext
argument_list|)
expr_stmt|;
name|Set
argument_list|<
name|Bundle
argument_list|>
name|bundles
init|=
name|bundleManager
operator|.
name|findBundlesWithFragmentsToRefresh
argument_list|(
name|existing
argument_list|,
name|installed
argument_list|)
decl_stmt|;
name|EasyMock
operator|.
name|verify
argument_list|(
name|bundleContext
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|bundles
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|hostBundle
argument_list|,
name|bundles
operator|.
name|iterator
argument_list|()
operator|.
name|next
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testfindBundlestoRefreshWithOptionalPackages
parameter_list|()
throws|throws
name|Exception
block|{
name|Bundle
name|exporterBundle
init|=
name|createDummyBundle
argument_list|(
literal|12345l
argument_list|,
literal|"exporter"
argument_list|,
name|headers
argument_list|(
name|Constants
operator|.
name|EXPORT_PACKAGE
argument_list|,
literal|"org.my.package"
argument_list|)
argument_list|)
decl_stmt|;
name|Bundle
name|importerBundle
init|=
name|createDummyBundle
argument_list|(
literal|54321l
argument_list|,
literal|"importer"
argument_list|,
name|headers
argument_list|(
name|Constants
operator|.
name|IMPORT_PACKAGE
argument_list|,
literal|"org.my.package;resolution:=optional"
argument_list|)
argument_list|)
decl_stmt|;
name|BundleContext
name|bundleContext
init|=
name|EasyMock
operator|.
name|createMock
argument_list|(
name|BundleContext
operator|.
name|class
argument_list|)
decl_stmt|;
name|BundleManager
name|bundleManager
init|=
operator|new
name|BundleManager
argument_list|(
name|bundleContext
argument_list|)
decl_stmt|;
comment|// Importer was already installed, exporter is new
name|Set
argument_list|<
name|Bundle
argument_list|>
name|existing
init|=
operator|new
name|HashSet
argument_list|<
name|Bundle
argument_list|>
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
name|importerBundle
argument_list|,
name|exporterBundle
argument_list|)
argument_list|)
decl_stmt|;
name|Set
argument_list|<
name|Bundle
argument_list|>
name|installed
init|=
operator|new
name|HashSet
argument_list|<
name|Bundle
argument_list|>
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
name|exporterBundle
argument_list|)
argument_list|)
decl_stmt|;
name|replay
argument_list|(
name|bundleContext
argument_list|)
expr_stmt|;
name|Set
argument_list|<
name|Bundle
argument_list|>
name|bundles
init|=
name|bundleManager
operator|.
name|findBundlesWithOptionalPackagesToRefresh
argument_list|(
name|existing
argument_list|,
name|installed
argument_list|)
decl_stmt|;
name|EasyMock
operator|.
name|verify
argument_list|(
name|bundleContext
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|bundles
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|importerBundle
argument_list|,
name|bundles
operator|.
name|iterator
argument_list|()
operator|.
name|next
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

