begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|main
package|;
end_package

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URI
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URISyntaxException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URL
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
specifier|public
class|class
name|FeatureReaderTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|testReadBundlesFromFeature
parameter_list|()
throws|throws
name|URISyntaxException
throws|,
name|Exception
block|{
name|URL
name|res
init|=
name|this
operator|.
name|getClass
argument_list|()
operator|.
name|getClassLoader
argument_list|()
operator|.
name|getResource
argument_list|(
literal|"test-karaf-home/system/org/apache/karaf/features/framework/1.0.0/framework-1.0.0-features.xml"
argument_list|)
decl_stmt|;
name|List
argument_list|<
name|BundleInfo
argument_list|>
name|bundles
init|=
operator|new
name|FeatureReader
argument_list|()
operator|.
name|readBundles
argument_list|(
name|res
operator|.
name|toURI
argument_list|()
argument_list|,
literal|"framework"
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|bundles
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|10
argument_list|,
name|bundles
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|.
name|startLevel
operator|.
name|intValue
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
operator|new
name|URI
argument_list|(
literal|"mvn:org.apache.aries.blueprint/org.apache.aries.blueprint.api/0.3.1"
argument_list|)
argument_list|,
name|bundles
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|.
name|uri
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

