begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *   http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|console
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|commands
operator|.
name|Command
import|;
end_import

begin_comment
comment|/**  * Exit from the current sub-shell and get back to the previous one.  */
end_comment

begin_class
annotation|@
name|Command
argument_list|(
name|scope
operator|=
literal|"*"
argument_list|,
name|name
operator|=
literal|"exit"
argument_list|,
name|description
operator|=
literal|"Exit from the current subshell"
argument_list|)
annotation|@
name|Deprecated
specifier|public
class|class
name|ExitAction
extends|extends
name|AbstractAction
block|{
specifier|public
name|Object
name|doExecute
parameter_list|()
throws|throws
name|Exception
block|{
comment|// get the current sub-shell
name|String
name|currentSubShell
init|=
operator|(
name|String
operator|)
name|session
operator|.
name|get
argument_list|(
literal|"SUBSHELL"
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|currentSubShell
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
if|if
condition|(
name|currentSubShell
operator|.
name|contains
argument_list|(
literal|":"
argument_list|)
condition|)
block|{
name|int
name|index
init|=
name|currentSubShell
operator|.
name|lastIndexOf
argument_list|(
literal|":"
argument_list|)
decl_stmt|;
name|session
operator|.
name|put
argument_list|(
literal|"SUBSHELL"
argument_list|,
name|currentSubShell
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
name|index
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|session
operator|.
name|put
argument_list|(
literal|"SUBSHELL"
argument_list|,
literal|""
argument_list|)
expr_stmt|;
block|}
name|String
name|currentScope
init|=
operator|(
name|String
operator|)
name|session
operator|.
name|get
argument_list|(
literal|"SCOPE"
argument_list|)
decl_stmt|;
name|int
name|index
init|=
name|currentScope
operator|.
name|indexOf
argument_list|(
literal|":"
argument_list|)
decl_stmt|;
name|session
operator|.
name|put
argument_list|(
literal|"SCOPE"
argument_list|,
name|currentScope
operator|.
name|substring
argument_list|(
name|index
operator|+
literal|1
argument_list|)
argument_list|)
expr_stmt|;
block|}
return|return
literal|null
return|;
block|}
block|}
end_class

end_unit

