begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|//
end_comment

begin_comment
comment|// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
end_comment

begin_comment
comment|// See<a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
end_comment

begin_comment
comment|// Any modifications to this file will be lost upon recompilation of the source schema.
end_comment

begin_comment
comment|// Generated on: 2011.01.19 at 04:45:46 PM PST
end_comment

begin_comment
comment|//
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|features
operator|.
name|internal
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessorType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAttribute
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlSchemaType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlValue
import|;
end_import

begin_comment
comment|/**  *   * Deployable element to install.  *               *   *<p>Java class for bundle complex type.  *   *<p>The following schema fragment specifies the expected content contained within this class.  *   *<pre>  *&lt;complexType name="bundle">  *&lt;simpleContent>  *&lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">  *&lt;attribute name="start-level" type="{http://www.w3.org/2001/XMLSchema}int" />  *&lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}boolean" />  *&lt;attribute name="dependency" type="{http://www.w3.org/2001/XMLSchema}boolean" />  *&lt;/extension>  *&lt;/simpleContent>  *&lt;/complexType>  *</pre>  *   *   */
end_comment

begin_class
annotation|@
name|XmlAccessorType
argument_list|(
name|XmlAccessType
operator|.
name|FIELD
argument_list|)
annotation|@
name|XmlType
argument_list|(
name|name
operator|=
literal|"bundle"
argument_list|,
name|propOrder
operator|=
block|{
literal|"value"
block|}
argument_list|)
specifier|public
class|class
name|Bundle
block|{
annotation|@
name|XmlValue
annotation|@
name|XmlSchemaType
argument_list|(
name|name
operator|=
literal|"anyURI"
argument_list|)
specifier|protected
name|String
name|value
decl_stmt|;
annotation|@
name|XmlAttribute
argument_list|(
name|name
operator|=
literal|"start-level"
argument_list|)
specifier|protected
name|Integer
name|startLevel
decl_stmt|;
annotation|@
name|XmlAttribute
specifier|protected
name|Boolean
name|start
decl_stmt|;
annotation|@
name|XmlAttribute
specifier|protected
name|Boolean
name|dependency
decl_stmt|;
comment|/**      * Gets the value of the value property.      *       * @return      *     possible object is      *     {@link String }      *           */
specifier|public
name|String
name|getValue
parameter_list|()
block|{
return|return
name|value
return|;
block|}
comment|/**      * Sets the value of the value property.      *       * @param value      *     allowed object is      *     {@link String }      *           */
specifier|public
name|void
name|setValue
parameter_list|(
name|String
name|value
parameter_list|)
block|{
name|this
operator|.
name|value
operator|=
name|value
expr_stmt|;
block|}
comment|/**      * Gets the value of the startLevel property.      *       * @return      *     possible object is      *     {@link Integer }      *           */
specifier|public
name|Integer
name|getStartLevel
parameter_list|()
block|{
return|return
name|startLevel
return|;
block|}
comment|/**      * Sets the value of the startLevel property.      *       * @param value      *     allowed object is      *     {@link Integer }      *           */
specifier|public
name|void
name|setStartLevel
parameter_list|(
name|Integer
name|value
parameter_list|)
block|{
name|this
operator|.
name|startLevel
operator|=
name|value
expr_stmt|;
block|}
comment|/**      * Gets the value of the start property.      *       * @return      *     possible object is      *     {@link Boolean }      *           */
specifier|public
name|Boolean
name|isStart
parameter_list|()
block|{
return|return
name|start
return|;
block|}
comment|/**      * Sets the value of the start property.      *       * @param value      *     allowed object is      *     {@link Boolean }      *           */
specifier|public
name|void
name|setStart
parameter_list|(
name|Boolean
name|value
parameter_list|)
block|{
name|this
operator|.
name|start
operator|=
name|value
expr_stmt|;
block|}
comment|/**      * Gets the value of the dependency property.      *       * @return      *     possible object is      *     {@link Boolean }      *           */
specifier|public
name|Boolean
name|isDependency
parameter_list|()
block|{
return|return
name|dependency
return|;
block|}
comment|/**      * Sets the value of the dependency property.      *       * @param value      *     allowed object is      *     {@link Boolean }      *           */
specifier|public
name|void
name|setDependency
parameter_list|(
name|Boolean
name|value
parameter_list|)
block|{
name|this
operator|.
name|dependency
operator|=
name|value
expr_stmt|;
block|}
block|}
end_class

end_unit

