begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|scheduler
operator|.
name|core
package|;
end_package

begin_import
import|import
name|org
operator|.
name|quartz
operator|.
name|Scheduler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|quartz
operator|.
name|SchedulerException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|quartz
operator|.
name|core
operator|.
name|QuartzSchedulerResources
import|;
end_import

begin_import
import|import
name|org
operator|.
name|quartz
operator|.
name|impl
operator|.
name|StdSchedulerFactory
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Properties
import|;
end_import

begin_class
specifier|public
class|class
name|KarafStdSchedulerFactory
extends|extends
name|StdSchedulerFactory
block|{
specifier|public
name|KarafStdSchedulerFactory
parameter_list|()
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"Not supported. Use: org.apache.karaf.scheduler.core.KarafStdSchedulerFactory(java.util.Properties)"
argument_list|)
throw|;
block|}
specifier|public
name|KarafStdSchedulerFactory
parameter_list|(
specifier|final
name|Properties
name|properties
parameter_list|)
throws|throws
name|SchedulerException
block|{
name|super
argument_list|(
name|properties
argument_list|)
expr_stmt|;
block|}
specifier|public
name|KarafStdSchedulerFactory
parameter_list|(
specifier|final
name|String
name|fileName
parameter_list|)
throws|throws
name|SchedulerException
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"Not supported. Use: org.apache.karaf.scheduler.core.KarafStdSchedulerFactory(java.util.Properties)"
argument_list|)
throw|;
block|}
specifier|public
name|Scheduler
name|instantiate
parameter_list|(
specifier|final
name|QuartzSchedulerResources
name|resources
parameter_list|,
specifier|final
name|org
operator|.
name|quartz
operator|.
name|core
operator|.
name|QuartzScheduler
name|quartzScheduler
parameter_list|)
block|{
specifier|final
name|Scheduler
name|scheduler
init|=
operator|new
name|KarafStdScheduler
argument_list|(
name|quartzScheduler
argument_list|)
decl_stmt|;
return|return
name|scheduler
return|;
block|}
block|}
end_class

end_unit

