begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|//
end_comment

begin_comment
comment|// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
end_comment

begin_comment
comment|// See<a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
end_comment

begin_comment
comment|// Any modifications to this file will be lost upon recompilation of the source schema.
end_comment

begin_comment
comment|// Generated on: 2011.10.28 at 03:20:55 PM PDT
end_comment

begin_comment
comment|//
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|region
operator|.
name|persist
operator|.
name|model
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|JAXBElement
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlElementDecl
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlRegistry
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|namespace
operator|.
name|QName
import|;
end_import

begin_comment
comment|/**  * This object contains factory methods for each   * Java content interface and Java element interface   * generated in the org.apache.karaf.region.persist.model package.   *<p>An ObjectFactory allows you to programatically   * construct new instances of the Java representation   * for XML content. The Java representation of XML   * content can consist of schema derived interfaces   * and classes representing the binding of schema   * type definitions, element declarations and model   * groups.  Factory methods for each of these are   * provided in this class.  *   */
end_comment

begin_class
annotation|@
name|XmlRegistry
specifier|public
class|class
name|ObjectFactory
block|{
specifier|private
specifier|final
specifier|static
name|QName
name|_Regions_QNAME
init|=
operator|new
name|QName
argument_list|(
literal|"http://karaf.apache.org/xmlns/region/v1.0.0"
argument_list|,
literal|"regions"
argument_list|)
decl_stmt|;
comment|/**      * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.karaf.region.persist.model      *       */
specifier|public
name|ObjectFactory
parameter_list|()
block|{     }
comment|/**      * Create an instance of {@link FilterNamespaceType }      *       */
specifier|public
name|FilterNamespaceType
name|createFilterNamespaceType
parameter_list|()
block|{
return|return
operator|new
name|FilterNamespaceType
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link FilterType }      *       */
specifier|public
name|FilterType
name|createFilterType
parameter_list|()
block|{
return|return
operator|new
name|FilterType
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link RegionBundleType }      *       */
specifier|public
name|RegionBundleType
name|createRegionBundleType
parameter_list|()
block|{
return|return
operator|new
name|RegionBundleType
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link FilterBundleType }      *       */
specifier|public
name|FilterBundleType
name|createFilterBundleType
parameter_list|()
block|{
return|return
operator|new
name|FilterBundleType
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link FilterPackageType }      *       */
specifier|public
name|FilterPackageType
name|createFilterPackageType
parameter_list|()
block|{
return|return
operator|new
name|FilterPackageType
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link FilterAttributeType }      *       */
specifier|public
name|FilterAttributeType
name|createFilterAttributeType
parameter_list|()
block|{
return|return
operator|new
name|FilterAttributeType
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link RegionType }      *       */
specifier|public
name|RegionType
name|createRegionType
parameter_list|()
block|{
return|return
operator|new
name|RegionType
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link RegionsType }      *       */
specifier|public
name|RegionsType
name|createRegionsType
parameter_list|()
block|{
return|return
operator|new
name|RegionsType
argument_list|()
return|;
block|}
comment|/**      * Create an instance of {@link JAXBElement }{@code<}{@link RegionsType }{@code>}}      *       */
annotation|@
name|XmlElementDecl
argument_list|(
name|namespace
operator|=
literal|"http://karaf.apache.org/xmlns/region/v1.0.0"
argument_list|,
name|name
operator|=
literal|"regions"
argument_list|)
specifier|public
name|JAXBElement
argument_list|<
name|RegionsType
argument_list|>
name|createRegions
parameter_list|(
name|RegionsType
name|value
parameter_list|)
block|{
return|return
operator|new
name|JAXBElement
argument_list|<
name|RegionsType
argument_list|>
argument_list|(
name|_Regions_QNAME
argument_list|,
name|RegionsType
operator|.
name|class
argument_list|,
literal|null
argument_list|,
name|value
argument_list|)
return|;
block|}
block|}
end_class

end_unit

