begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|karaf
operator|.
name|gshell
operator|.
name|core
operator|.
name|vfs
operator|.
name|mvn
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|vfs
operator|.
name|FileName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|vfs
operator|.
name|FileObject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|vfs
operator|.
name|FileSystemOptions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|vfs
operator|.
name|provider
operator|.
name|url
operator|.
name|UrlFileSystem
import|;
end_import

begin_class
specifier|public
class|class
name|MvnFileSystem
extends|extends
name|UrlFileSystem
block|{
specifier|protected
name|MvnFileSystem
parameter_list|(
name|FileName
name|fileName
parameter_list|,
name|FileSystemOptions
name|fileSystemOptions
parameter_list|)
block|{
name|super
argument_list|(
name|fileName
argument_list|,
name|fileSystemOptions
argument_list|)
expr_stmt|;
block|}
specifier|protected
name|FileObject
name|createFile
parameter_list|(
name|FileName
name|fileName
parameter_list|)
block|{
return|return
operator|new
name|MvnFileObject
argument_list|(
name|this
argument_list|,
name|fileName
argument_list|)
return|;
block|}
block|}
end_class

end_unit

