begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|web
operator|.
name|commands
package|;
end_package

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Desktop
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URI
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|api
operator|.
name|action
operator|.
name|Action
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|api
operator|.
name|action
operator|.
name|Argument
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|api
operator|.
name|action
operator|.
name|Command
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|api
operator|.
name|action
operator|.
name|Option
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|api
operator|.
name|action
operator|.
name|lifecycle
operator|.
name|Reference
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|api
operator|.
name|action
operator|.
name|lifecycle
operator|.
name|Service
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|web
operator|.
name|WebContainerService
import|;
end_import

begin_class
annotation|@
name|Command
argument_list|(
name|scope
operator|=
literal|"web"
argument_list|,
name|name
operator|=
literal|"launch"
argument_list|,
name|description
operator|=
literal|"Start the web application in a browser of the given bundle ID."
argument_list|)
annotation|@
name|Service
specifier|public
class|class
name|Launch
implements|implements
name|Action
block|{
annotation|@
name|Argument
argument_list|(
name|index
operator|=
literal|0
argument_list|,
name|name
operator|=
literal|"id"
argument_list|,
name|description
operator|=
literal|"The bundle ID to start the browser with"
argument_list|,
name|required
operator|=
literal|true
argument_list|,
name|multiValued
operator|=
literal|false
argument_list|)
name|Long
name|id
decl_stmt|;
annotation|@
name|Option
argument_list|(
name|name
operator|=
literal|"--base"
argument_list|,
name|description
operator|=
literal|"The base URL to browse to, otherwise default localhost:8181 will be used."
argument_list|,
name|required
operator|=
literal|false
argument_list|)
name|String
name|baseUrl
init|=
literal|null
decl_stmt|;
annotation|@
name|Reference
specifier|private
name|WebContainerService
name|webContainerService
decl_stmt|;
specifier|public
name|void
name|setWebContainerService
parameter_list|(
name|WebContainerService
name|webContainerService
parameter_list|)
block|{
name|this
operator|.
name|webContainerService
operator|=
name|webContainerService
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|Object
name|execute
parameter_list|()
throws|throws
name|Exception
block|{
name|String
name|webContextPath
init|=
name|webContainerService
operator|.
name|getWebContextPath
argument_list|(
name|id
argument_list|)
decl_stmt|;
if|if
condition|(
name|baseUrl
operator|==
literal|null
condition|)
name|baseUrl
operator|=
literal|"http://localhost:8181"
expr_stmt|;
if|if
condition|(
operator|!
name|webContextPath
operator|.
name|startsWith
argument_list|(
literal|"/"
argument_list|)
condition|)
name|webContextPath
operator|=
literal|"/"
operator|+
name|webContextPath
expr_stmt|;
name|String
name|uri
init|=
name|baseUrl
operator|+
name|webContextPath
decl_stmt|;
name|Desktop
operator|.
name|getDesktop
argument_list|()
operator|.
name|browse
argument_list|(
operator|new
name|URI
argument_list|(
name|uri
argument_list|)
argument_list|)
expr_stmt|;
return|return
literal|null
return|;
block|}
block|}
end_class

end_unit

