begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|tooling
operator|.
name|exam
operator|.
name|options
package|;
end_package

begin_import
import|import
name|org
operator|.
name|ops4j
operator|.
name|pax
operator|.
name|exam
operator|.
name|Option
import|;
end_import

begin_comment
comment|/**  * Abstract configuration file option. This one should not used directly but rather via  * {@link KarafDistributionConfigurationFileExtendOption} or {@link KarafDistributionConfigurationFilePutOption}.  */
end_comment

begin_class
specifier|public
specifier|abstract
class|class
name|KarafDistributionConfigurationFileOption
implements|implements
name|Option
block|{
specifier|private
name|String
name|configurationFilePath
decl_stmt|;
specifier|private
name|String
name|key
decl_stmt|;
specifier|private
name|String
name|value
decl_stmt|;
specifier|public
name|KarafDistributionConfigurationFileOption
parameter_list|(
name|ConfigurationPointer
name|pointer
parameter_list|,
name|String
name|value
parameter_list|)
block|{
name|this
argument_list|(
name|pointer
operator|.
name|getConfigurationFilePath
argument_list|()
argument_list|,
name|pointer
operator|.
name|getKey
argument_list|()
argument_list|,
name|value
argument_list|)
expr_stmt|;
block|}
specifier|public
name|KarafDistributionConfigurationFileOption
parameter_list|(
name|String
name|configurationFilePath
parameter_list|,
name|String
name|key
parameter_list|,
name|String
name|value
parameter_list|)
block|{
name|this
operator|.
name|configurationFilePath
operator|=
name|configurationFilePath
expr_stmt|;
name|this
operator|.
name|key
operator|=
name|key
expr_stmt|;
name|this
operator|.
name|value
operator|=
name|value
expr_stmt|;
block|}
specifier|public
name|KarafDistributionConfigurationFileOption
parameter_list|(
name|String
name|configurationFilePath
parameter_list|)
block|{
name|this
operator|.
name|configurationFilePath
operator|=
name|configurationFilePath
expr_stmt|;
block|}
specifier|public
name|String
name|getConfigurationFilePath
parameter_list|()
block|{
return|return
name|configurationFilePath
return|;
block|}
specifier|public
name|String
name|getKey
parameter_list|()
block|{
return|return
name|key
return|;
block|}
specifier|public
name|String
name|getValue
parameter_list|()
block|{
return|return
name|value
return|;
block|}
block|}
end_class

end_unit

