begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|features
operator|.
name|internal
operator|.
name|model
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAccessorType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlAttribute
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlType
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlValue
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|features
operator|.
name|ConfigFileInfo
import|;
end_import

begin_comment
comment|/**  *<p>Additional configuration files which should be created during feature installation.</p>  *<p>Java class for configFile complex type.</p>  *<p>The following schema fragment specifies the expected content contained within this class.</p>  *<pre>  *&lt;complexType name="configFile"&gt;  *&lt;simpleContent&gt;  *&lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;  *&lt;attribute name="finalname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;  *&lt;attribute name="override" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;  *&lt;/extension&gt;  *&lt;/simpleContent&gt;  *&lt;/complexType&gt;  *</pre>  */
end_comment

begin_class
annotation|@
name|XmlAccessorType
argument_list|(
name|XmlAccessType
operator|.
name|FIELD
argument_list|)
annotation|@
name|XmlType
argument_list|(
name|name
operator|=
literal|"configFile"
argument_list|,
name|propOrder
operator|=
block|{
literal|"value"
block|}
argument_list|)
specifier|public
class|class
name|ConfigFile
implements|implements
name|ConfigFileInfo
block|{
annotation|@
name|XmlValue
specifier|protected
name|String
name|value
decl_stmt|;
annotation|@
name|XmlAttribute
argument_list|(
name|required
operator|=
literal|true
argument_list|)
specifier|protected
name|String
name|finalname
decl_stmt|;
annotation|@
name|XmlAttribute
specifier|protected
name|Boolean
name|override
decl_stmt|;
comment|/**      * Gets the value of the value property.      *      * @return possible object is      * {@link String }      */
specifier|public
name|String
name|getLocation
parameter_list|()
block|{
return|return
name|value
return|;
block|}
comment|/**      * Sets the value of the value property.      *      * @param value allowed object is      *              {@link String }      */
specifier|public
name|void
name|setLocation
parameter_list|(
name|String
name|value
parameter_list|)
block|{
name|this
operator|.
name|value
operator|=
name|value
expr_stmt|;
block|}
comment|/**      * Gets the value of the finalname property.      *      * @return possible object is      * {@link String }      */
specifier|public
name|String
name|getFinalname
parameter_list|()
block|{
return|return
name|finalname
return|;
block|}
comment|/**      * Sets the value of the finalname property.      *      * @param value allowed object is      *              {@link String }      */
specifier|public
name|void
name|setFinalname
parameter_list|(
name|String
name|value
parameter_list|)
block|{
name|this
operator|.
name|finalname
operator|=
name|value
expr_stmt|;
block|}
comment|/**      * Gets the value of the override property.      *      * @return possible object is      * {@link Boolean }      */
specifier|public
name|boolean
name|isOverride
parameter_list|()
block|{
return|return
name|override
operator|==
literal|null
condition|?
literal|false
else|:
name|override
return|;
block|}
comment|/**      * Sets the value of the override property.      *      * @param value allowed object is      *              {@link Boolean }      */
specifier|public
name|void
name|setOverride
parameter_list|(
name|Boolean
name|value
parameter_list|)
block|{
name|this
operator|.
name|override
operator|=
name|value
expr_stmt|;
block|}
block|}
end_class

end_unit

