begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|bundle
operator|.
name|core
operator|.
name|internal
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|LinkedHashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|regex
operator|.
name|Matcher
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|regex
operator|.
name|Pattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|Bundle
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|BundleContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|Constants
import|;
end_import

begin_class
specifier|public
class|class
name|BundleSelectorImpl
block|{
specifier|private
specifier|final
name|BundleContext
name|bundleContext
decl_stmt|;
specifier|public
name|BundleSelectorImpl
parameter_list|(
name|BundleContext
name|bundleContext
parameter_list|)
block|{
name|this
operator|.
name|bundleContext
operator|=
name|bundleContext
expr_stmt|;
block|}
specifier|public
name|List
argument_list|<
name|Bundle
argument_list|>
name|selectBundles
parameter_list|(
name|List
argument_list|<
name|String
argument_list|>
name|ids
parameter_list|,
name|boolean
name|defaultAllBundles
parameter_list|)
block|{
name|List
argument_list|<
name|Bundle
argument_list|>
name|bundles
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
if|if
condition|(
name|ids
operator|!=
literal|null
operator|&&
operator|!
name|ids
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
for|for
control|(
name|String
name|id
range|:
name|ids
control|)
block|{
if|if
condition|(
name|id
operator|==
literal|null
condition|)
block|{
continue|continue;
block|}
name|addMatchingBundles
argument_list|(
name|id
argument_list|,
name|bundles
argument_list|)
expr_stmt|;
block|}
block|}
elseif|else
if|if
condition|(
name|defaultAllBundles
condition|)
block|{
name|Collections
operator|.
name|addAll
argument_list|(
name|bundles
argument_list|,
name|bundleContext
operator|.
name|getBundles
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|List
argument_list|<
name|Bundle
argument_list|>
name|filteredBundleList
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|(
operator|new
name|LinkedHashSet
argument_list|<>
argument_list|(
name|bundles
argument_list|)
argument_list|)
decl_stmt|;
return|return
name|filteredBundleList
return|;
block|}
specifier|private
name|void
name|addMatchingBundles
parameter_list|(
name|String
name|id
parameter_list|,
name|List
argument_list|<
name|Bundle
argument_list|>
name|bundles
parameter_list|)
block|{
comment|// id is a number
name|Pattern
name|pattern
init|=
name|Pattern
operator|.
name|compile
argument_list|(
literal|"^\\d+$"
argument_list|)
decl_stmt|;
name|Matcher
name|matcher
init|=
name|pattern
operator|.
name|matcher
argument_list|(
name|id
argument_list|)
decl_stmt|;
if|if
condition|(
name|matcher
operator|.
name|matches
argument_list|()
condition|)
block|{
name|Bundle
name|bundle
init|=
name|this
operator|.
name|getBundleById
argument_list|(
name|id
argument_list|)
decl_stmt|;
name|addBundle
argument_list|(
name|bundle
argument_list|,
name|id
argument_list|,
name|bundles
argument_list|)
expr_stmt|;
return|return;
block|}
comment|// id as a number range
name|pattern
operator|=
name|Pattern
operator|.
name|compile
argument_list|(
literal|"^(\\d+)-(\\d+)$"
argument_list|)
expr_stmt|;
name|matcher
operator|=
name|pattern
operator|.
name|matcher
argument_list|(
name|id
argument_list|)
expr_stmt|;
if|if
condition|(
name|matcher
operator|.
name|matches
argument_list|()
condition|)
block|{
name|int
name|index
init|=
name|id
operator|.
name|indexOf
argument_list|(
literal|'-'
argument_list|)
decl_stmt|;
name|long
name|startId
init|=
name|Long
operator|.
name|parseLong
argument_list|(
name|id
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
name|index
argument_list|)
argument_list|)
decl_stmt|;
name|long
name|endId
init|=
name|Long
operator|.
name|parseLong
argument_list|(
name|id
operator|.
name|substring
argument_list|(
name|index
operator|+
literal|1
argument_list|)
argument_list|)
decl_stmt|;
if|if
condition|(
name|startId
operator|<
name|endId
condition|)
block|{
for|for
control|(
name|long
name|i
init|=
name|startId
init|;
name|i
operator|<=
name|endId
condition|;
name|i
operator|++
control|)
block|{
name|Bundle
name|bundle
init|=
name|bundleContext
operator|.
name|getBundle
argument_list|(
name|i
argument_list|)
decl_stmt|;
name|addBundle
argument_list|(
name|bundle
argument_list|,
name|String
operator|.
name|valueOf
argument_list|(
name|i
argument_list|)
argument_list|,
name|bundles
argument_list|)
expr_stmt|;
block|}
block|}
return|return;
block|}
comment|// bundles by name
name|int
name|index
init|=
name|id
operator|.
name|indexOf
argument_list|(
literal|'/'
argument_list|)
decl_stmt|;
name|List
argument_list|<
name|Bundle
argument_list|>
name|bundlesByName
decl_stmt|;
if|if
condition|(
name|index
operator|!=
operator|-
literal|1
condition|)
block|{
comment|// user has provided name and version
name|bundlesByName
operator|=
name|getBundleByNameAndVersion
argument_list|(
name|id
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
name|index
argument_list|)
argument_list|,
name|id
operator|.
name|substring
argument_list|(
name|index
operator|+
literal|1
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// user has provided only the name
name|bundlesByName
operator|=
name|getBundleByName
argument_list|(
name|id
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|Bundle
name|bundleByName
range|:
name|bundlesByName
control|)
block|{
name|addBundle
argument_list|(
name|bundleByName
argument_list|,
name|id
argument_list|,
name|bundles
argument_list|)
expr_stmt|;
block|}
comment|// bundles by location
name|List
argument_list|<
name|Bundle
argument_list|>
name|bundlesByLocation
init|=
name|getBundlesByLocation
argument_list|(
name|id
argument_list|)
decl_stmt|;
for|for
control|(
name|Bundle
name|bundleByLocation
range|:
name|bundlesByLocation
control|)
block|{
name|addBundle
argument_list|(
name|bundleByLocation
argument_list|,
name|id
argument_list|,
name|bundles
argument_list|)
expr_stmt|;
block|}
block|}
specifier|private
name|void
name|addBundle
parameter_list|(
name|Bundle
name|bundle
parameter_list|,
name|String
name|id
parameter_list|,
name|List
argument_list|<
name|Bundle
argument_list|>
name|bundles
parameter_list|)
block|{
if|if
condition|(
name|bundle
operator|==
literal|null
condition|)
block|{
comment|// if the bundle is null here, it's because we didn't find it
name|System
operator|.
name|err
operator|.
name|println
argument_list|(
literal|"Bundle "
operator|+
name|id
operator|+
literal|" is invalid"
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|bundles
operator|.
name|add
argument_list|(
name|bundle
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Get a bundle identified by an id number.      *      * @param id the id number.      * @return the bundle or null if not found.      */
specifier|private
name|Bundle
name|getBundleById
parameter_list|(
name|String
name|id
parameter_list|)
block|{
name|Bundle
name|bundle
init|=
literal|null
decl_stmt|;
try|try
block|{
name|long
name|idNumber
init|=
name|Long
operator|.
name|parseLong
argument_list|(
name|id
argument_list|)
decl_stmt|;
name|bundle
operator|=
name|bundleContext
operator|.
name|getBundle
argument_list|(
name|idNumber
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|NumberFormatException
name|nfe
parameter_list|)
block|{
comment|// ignore
block|}
return|return
name|bundle
return|;
block|}
comment|/**      * Get a bundles list with the name or symbolic name matching the pattern.      *      * @param name the bundle name or symbolic name pattern to match.      * @return the bundles list.      */
specifier|private
name|List
argument_list|<
name|Bundle
argument_list|>
name|getBundleByName
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|getBundleByNameAndVersion
argument_list|(
name|name
argument_list|,
literal|null
argument_list|)
return|;
block|}
comment|/**      * Get a bundles list with the name or symbolic name matching the name pattern and version matching the version pattern.      *      * @param name    the bundle name or symbolic name regex to match.      * @param version the bundle version regex to match.      * @return the bundles list.      */
specifier|private
name|List
argument_list|<
name|Bundle
argument_list|>
name|getBundleByNameAndVersion
parameter_list|(
name|String
name|name
parameter_list|,
name|String
name|version
parameter_list|)
block|{
name|Bundle
index|[]
name|bundles
init|=
name|bundleContext
operator|.
name|getBundles
argument_list|()
decl_stmt|;
name|ArrayList
argument_list|<
name|Bundle
argument_list|>
name|result
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
name|Pattern
name|namePattern
init|=
name|Pattern
operator|.
name|compile
argument_list|(
name|name
argument_list|)
decl_stmt|;
for|for
control|(
name|Bundle
name|bundle
range|:
name|bundles
control|)
block|{
name|String
name|bundleSymbolicName
init|=
name|bundle
operator|.
name|getSymbolicName
argument_list|()
decl_stmt|;
comment|// skip bundles without Bundle-SymbolicName header
if|if
condition|(
name|bundleSymbolicName
operator|==
literal|null
condition|)
block|{
continue|continue;
block|}
name|Matcher
name|symbolicNameMatcher
init|=
name|namePattern
operator|.
name|matcher
argument_list|(
name|bundleSymbolicName
argument_list|)
decl_stmt|;
name|Matcher
name|nameMatcher
init|=
literal|null
decl_stmt|;
name|String
name|bundleName
init|=
name|bundle
operator|.
name|getHeaders
argument_list|()
operator|.
name|get
argument_list|(
name|Constants
operator|.
name|BUNDLE_NAME
argument_list|)
decl_stmt|;
if|if
condition|(
name|bundleName
operator|!=
literal|null
condition|)
block|{
name|nameMatcher
operator|=
name|namePattern
operator|.
name|matcher
argument_list|(
name|bundleName
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|version
operator|!=
literal|null
condition|)
block|{
name|String
name|bundleVersion
init|=
name|bundle
operator|.
name|getHeaders
argument_list|()
operator|.
name|get
argument_list|(
name|Constants
operator|.
name|BUNDLE_VERSION
argument_list|)
decl_stmt|;
if|if
condition|(
name|bundleVersion
operator|!=
literal|null
condition|)
block|{
name|boolean
name|nameMatch
init|=
operator|(
name|nameMatcher
operator|!=
literal|null
operator|&&
name|nameMatcher
operator|.
name|matches
argument_list|()
operator|)
operator|||
name|symbolicNameMatcher
operator|.
name|matches
argument_list|()
decl_stmt|;
if|if
condition|(
name|nameMatch
condition|)
block|{
name|Pattern
name|versionPattern
init|=
name|Pattern
operator|.
name|compile
argument_list|(
name|version
argument_list|)
decl_stmt|;
name|Matcher
name|versionMatcher
init|=
name|versionPattern
operator|.
name|matcher
argument_list|(
name|bundleVersion
argument_list|)
decl_stmt|;
if|if
condition|(
name|versionMatcher
operator|.
name|matches
argument_list|()
condition|)
block|{
name|result
operator|.
name|add
argument_list|(
name|bundle
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
else|else
block|{
name|boolean
name|nameMatch
init|=
operator|(
name|nameMatcher
operator|!=
literal|null
operator|&&
name|nameMatcher
operator|.
name|matches
argument_list|()
operator|)
operator|||
name|symbolicNameMatcher
operator|.
name|matches
argument_list|()
decl_stmt|;
if|if
condition|(
name|nameMatch
condition|)
block|{
name|result
operator|.
name|add
argument_list|(
name|bundle
argument_list|)
expr_stmt|;
block|}
block|}
block|}
return|return
name|result
return|;
block|}
specifier|private
name|List
argument_list|<
name|Bundle
argument_list|>
name|getBundlesByLocation
parameter_list|(
name|String
name|url
parameter_list|)
block|{
name|Bundle
index|[]
name|bundles
init|=
name|bundleContext
operator|.
name|getBundles
argument_list|()
decl_stmt|;
name|ArrayList
argument_list|<
name|Bundle
argument_list|>
name|result
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
name|Pattern
name|locationPattern
init|=
name|Pattern
operator|.
name|compile
argument_list|(
name|url
argument_list|)
decl_stmt|;
for|for
control|(
name|Bundle
name|bundle
range|:
name|bundles
control|)
block|{
name|Matcher
name|locationMatcher
init|=
name|locationPattern
operator|.
name|matcher
argument_list|(
name|bundle
operator|.
name|getLocation
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|locationMatcher
operator|.
name|matches
argument_list|()
condition|)
block|{
name|result
operator|.
name|add
argument_list|(
name|bundle
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|result
return|;
block|}
block|}
end_class

end_unit

