begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|config
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Dictionary
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|console
operator|.
name|OsgiCommandSupport
import|;
end_import

begin_comment
comment|/**  * Abstract class from which all commands related to the ConfigurationAdmin  * service should derive.  * This command retrieves a reference to the ConfigurationAdmin service before  * calling another method to actually process the command.  */
end_comment

begin_class
specifier|public
specifier|abstract
class|class
name|ConfigCommandSupport
extends|extends
name|OsgiCommandSupport
block|{
specifier|public
specifier|static
specifier|final
name|String
name|PROPERTY_CONFIG_PID
init|=
literal|"ConfigCommand.PID"
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|PROPERTY_CONFIG_PROPS
init|=
literal|"ConfigCommand.Props"
decl_stmt|;
specifier|protected
name|ConfigRepository
name|configRepository
decl_stmt|;
annotation|@
name|SuppressWarnings
argument_list|(
literal|"rawtypes"
argument_list|)
specifier|protected
name|Dictionary
name|getEditedProps
parameter_list|()
throws|throws
name|Exception
block|{
return|return
operator|(
name|Dictionary
operator|)
name|this
operator|.
name|session
operator|.
name|get
argument_list|(
name|PROPERTY_CONFIG_PROPS
argument_list|)
return|;
block|}
specifier|public
name|void
name|setConfigRepository
parameter_list|(
name|ConfigRepository
name|configRepository
parameter_list|)
block|{
name|this
operator|.
name|configRepository
operator|=
name|configRepository
expr_stmt|;
block|}
block|}
end_class

end_unit

