begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|karaf
operator|.
name|shell
operator|.
name|dev
operator|.
name|framework
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_comment
comment|/**  * Represents Apache Felix as the underlying OSGi platform  */
end_comment

begin_class
specifier|public
class|class
name|Felix
extends|extends
name|Framework
block|{
comment|/**      * Create a instance of Karaf running with Felix in the given base directory      *      * @param base the base directory      */
specifier|public
name|Felix
parameter_list|(
name|File
name|base
parameter_list|)
block|{
name|super
argument_list|(
name|base
argument_list|)
expr_stmt|;
block|}
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
literal|"Felix"
return|;
block|}
specifier|public
name|void
name|enableDebug
parameter_list|(
name|File
name|directory
parameter_list|)
throws|throws
name|IOException
block|{
name|setConfigProperty
argument_list|(
literal|"felix.log.level"
argument_list|,
literal|"4"
argument_list|)
expr_stmt|;
name|saveConfigProperties
argument_list|()
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|printf
argument_list|(
literal|"- set felix.log.level=4 in etc/config.properties%n%n"
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|printf
argument_list|(
literal|"Restart Karaf now to enable Felix debug logging%n"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|disableDebug
parameter_list|(
name|File
name|directory
parameter_list|)
throws|throws
name|IOException
block|{
name|removeConfigProperty
argument_list|(
literal|"felix.log.level"
argument_list|)
expr_stmt|;
name|saveConfigProperties
argument_list|()
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|printf
argument_list|(
literal|"- removed felix.log.level from etc/config.properties%n%n"
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|printf
argument_list|(
literal|"Restart Karaf now to disable Felix debug logging%n"
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

