begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|util
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|util
operator|.
name|bundles
operator|.
name|BundleUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|FileInputStream
import|;
end_import

begin_class
specifier|public
class|class
name|BundleUtilsTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|testJavaxMail
parameter_list|()
throws|throws
name|Exception
block|{
name|String
name|url
init|=
name|getClass
argument_list|()
operator|.
name|getClassLoader
argument_list|()
operator|.
name|getResource
argument_list|(
literal|"com/sun/mail/util/ASCIIUtility.class"
argument_list|)
operator|.
name|toString
argument_list|()
decl_stmt|;
name|url
operator|=
name|url
operator|.
name|substring
argument_list|(
literal|"jar:file:"
operator|.
name|length
argument_list|()
argument_list|,
name|url
operator|.
name|indexOf
argument_list|(
literal|"!/"
argument_list|)
argument_list|)
expr_stmt|;
name|File
name|file
init|=
operator|new
name|File
argument_list|(
name|url
argument_list|)
decl_stmt|;
name|BundleUtils
operator|.
name|fixBundleWithUpdateLocation
argument_list|(
operator|new
name|FileInputStream
argument_list|(
name|file
argument_list|)
argument_list|,
literal|"mvn:javax.mail/mail/1.4.7"
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

