begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|maven
operator|.
name|core
package|;
end_package

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|MalformedURLException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|hamcrest
operator|.
name|CoreMatchers
operator|.
name|equalTo
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|hamcrest
operator|.
name|MatcherAssert
operator|.
name|assertThat
import|;
end_import

begin_class
specifier|public
class|class
name|MavenRepositoryURLTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|uris
parameter_list|()
throws|throws
name|MalformedURLException
block|{
name|String
name|uri1
decl_stmt|,
name|uri2
decl_stmt|;
name|MavenRepositoryURL
name|mavenURI
decl_stmt|;
name|uri1
operator|=
literal|"http://localhost/@id=id1@snapshots@update=interval:42@_from="
operator|+
name|MavenRepositoryURL
operator|.
name|FROM
operator|.
name|SETTINGS
expr_stmt|;
name|uri2
operator|=
literal|"http://localhost/@id=id1@snapshots@update=interval:42"
expr_stmt|;
name|mavenURI
operator|=
operator|new
name|MavenRepositoryURL
argument_list|(
name|uri1
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|mavenURI
operator|.
name|asRepositorySpec
argument_list|()
argument_list|,
name|equalTo
argument_list|(
name|uri2
argument_list|)
argument_list|)
expr_stmt|;
name|uri1
operator|=
literal|"http://localhost/@id=id1@snapshots@checksum=fail@_from="
operator|+
name|MavenRepositoryURL
operator|.
name|FROM
operator|.
name|SETTINGS
expr_stmt|;
name|uri2
operator|=
literal|"http://localhost/@id=id1@snapshots@checksum=fail"
expr_stmt|;
name|mavenURI
operator|=
operator|new
name|MavenRepositoryURL
argument_list|(
name|uri1
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|mavenURI
operator|.
name|asRepositorySpec
argument_list|()
argument_list|,
name|equalTo
argument_list|(
name|uri2
argument_list|)
argument_list|)
expr_stmt|;
name|uri1
operator|=
literal|"http://localhost/@id=id1@snapshots@noreleases@update=interval:42@_from="
operator|+
name|MavenRepositoryURL
operator|.
name|FROM
operator|.
name|SETTINGS
expr_stmt|;
name|uri2
operator|=
literal|"http://localhost/@id=id1@noreleases@snapshots@snapshotsUpdate=interval:42"
expr_stmt|;
name|mavenURI
operator|=
operator|new
name|MavenRepositoryURL
argument_list|(
name|uri1
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|mavenURI
operator|.
name|asRepositorySpec
argument_list|()
argument_list|,
name|equalTo
argument_list|(
name|uri2
argument_list|)
argument_list|)
expr_stmt|;
name|uri1
operator|=
literal|"http://localhost/@id=id1@update=interval:42@_from="
operator|+
name|MavenRepositoryURL
operator|.
name|FROM
operator|.
name|SETTINGS
expr_stmt|;
name|uri2
operator|=
literal|"http://localhost/@id=id1@releasesUpdate=interval:42"
expr_stmt|;
name|mavenURI
operator|=
operator|new
name|MavenRepositoryURL
argument_list|(
name|uri1
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|mavenURI
operator|.
name|asRepositorySpec
argument_list|()
argument_list|,
name|equalTo
argument_list|(
name|uri2
argument_list|)
argument_list|)
expr_stmt|;
name|uri1
operator|=
literal|"http://localhost/@id=id1@snapshots@noreleases@checksum=fail@_from="
operator|+
name|MavenRepositoryURL
operator|.
name|FROM
operator|.
name|SETTINGS
expr_stmt|;
name|uri2
operator|=
literal|"http://localhost/@id=id1@noreleases@snapshots@snapshotsChecksum=fail"
expr_stmt|;
name|mavenURI
operator|=
operator|new
name|MavenRepositoryURL
argument_list|(
name|uri1
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|mavenURI
operator|.
name|asRepositorySpec
argument_list|()
argument_list|,
name|equalTo
argument_list|(
name|uri2
argument_list|)
argument_list|)
expr_stmt|;
name|uri1
operator|=
literal|"http://localhost/@id=id1@checksum=fail@_from="
operator|+
name|MavenRepositoryURL
operator|.
name|FROM
operator|.
name|SETTINGS
expr_stmt|;
name|uri2
operator|=
literal|"http://localhost/@id=id1@releasesChecksum=fail"
expr_stmt|;
name|mavenURI
operator|=
operator|new
name|MavenRepositoryURL
argument_list|(
name|uri1
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|mavenURI
operator|.
name|asRepositorySpec
argument_list|()
argument_list|,
name|equalTo
argument_list|(
name|uri2
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

