begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *  http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|impl
operator|.
name|console
operator|.
name|osgi
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|felix
operator|.
name|service
operator|.
name|command
operator|.
name|CommandSessionListener
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|shell
operator|.
name|impl
operator|.
name|console
operator|.
name|SessionFactoryImpl
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|BundleContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|framework
operator|.
name|ServiceReference
import|;
end_import

begin_import
import|import
name|org
operator|.
name|osgi
operator|.
name|util
operator|.
name|tracker
operator|.
name|ServiceTracker
import|;
end_import

begin_comment
comment|/**  * Tracker for CommandSessionListener.  */
end_comment

begin_class
specifier|public
class|class
name|ListenerTracker
extends|extends
name|ServiceTracker
argument_list|<
name|CommandSessionListener
argument_list|,
name|CommandSessionListener
argument_list|>
block|{
specifier|private
name|SessionFactoryImpl
name|sessionFactory
decl_stmt|;
specifier|public
name|ListenerTracker
parameter_list|(
name|SessionFactoryImpl
name|sessionFactory
parameter_list|,
name|BundleContext
name|context
parameter_list|)
block|{
name|super
argument_list|(
name|context
argument_list|,
name|CommandSessionListener
operator|.
name|class
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|this
operator|.
name|sessionFactory
operator|=
name|sessionFactory
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|CommandSessionListener
name|addingService
parameter_list|(
name|ServiceReference
argument_list|<
name|CommandSessionListener
argument_list|>
name|reference
parameter_list|)
block|{
name|CommandSessionListener
name|service
init|=
name|super
operator|.
name|addingService
argument_list|(
name|reference
argument_list|)
decl_stmt|;
name|sessionFactory
operator|.
name|getCommandProcessor
argument_list|()
operator|.
name|addListener
argument_list|(
name|service
argument_list|)
expr_stmt|;
return|return
name|service
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|removedService
parameter_list|(
name|ServiceReference
argument_list|<
name|CommandSessionListener
argument_list|>
name|reference
parameter_list|,
name|CommandSessionListener
name|service
parameter_list|)
block|{
name|sessionFactory
operator|.
name|getCommandProcessor
argument_list|()
operator|.
name|removeListener
argument_list|(
name|service
argument_list|)
expr_stmt|;
name|super
operator|.
name|removedService
argument_list|(
name|reference
argument_list|,
name|service
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

