begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|karaf
operator|.
name|main
operator|.
name|lock
package|;
end_package

begin_comment
comment|/**  * Allows to react on events generated by the locking framework  */
end_comment

begin_interface
specifier|public
interface|interface
name|LockCallBack
block|{
name|void
name|lockAquired
parameter_list|()
function_decl|;
name|void
name|lockLost
parameter_list|()
function_decl|;
name|void
name|waitingForLock
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

